name: sharp_toggle_switch
description: SharpToggleSwitch.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

flutter: null