include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false

analyzer:
  errors:
    missing_required_param: warning
    parameter_assignments: warning
    missing_return: error
    todo: ignore