include: package:flutter_lints/flutter.yaml

linter:
  rules:

    # General linter rules.
    prefer_single_quotes: true
    avoid_print: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    require_trailing_commas: true
    prefer_final_locals: true
    prefer_final_fields: true
    library_private_types_in_public_api: true
    camel_case_types: true
    file_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    constant_identifier_names: true
    directives_ordering: true
    lines_longer_than_80_chars: true
    curly_braces_in_flow_control_structures: true
    prefer_interpolation_to_compose_strings: true
    prefer_collection_literals: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    prefer_expression_function_bodies: true
    prefer_initializing_formals: true
    type_init_formals: true
    empty_constructor_bodies: true
    empty_statements: true
    unnecessary_new: true
    unnecessary_this: true
    unnecessary_const: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_lambdas: true
    unnecessary_getters_setters: true
    unnecessary_string_interpolations: true
    avoid_setters_without_getters: true
    avoid_returning_null: true
    avoid_return_types_on_setters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    package_api_docs: true
    package_prefixed_library_names: true
    prefer_relative_imports: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    await_only_futures: true
    cascade_invocations: true
    no_runtimeType_toString: true

    # Package related linter rules.
    slash_for_doc_comments: true
    comment_references: true

analyzer:
  errors:
    missing_required_param: warning
    parameter_assignments: warning
    missing_return: error
    todo: ignore